# Word2Vec
Word2Vec is a word embedding technique that converts words into numerical vectors based on their surrounding context.

It helps capture relationships between words, where words with similar meanings or contexts can have similar vector representations.

In [1]:
!pip install gensim

   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
    --------------------------------------- 0.5/24.4 MB 5.6 MB/s eta 0:00:05
   -- ------------------------------------- 1.6/24.4 MB 8.3 MB/s eta 0:00:03
   ----- ---------------------------------- 3.4/24.4 MB 6.7 MB/s eta 0:00:04
   --------- ------------------------------ 5.8/24.4 MB 8.2 MB/s eta 0:00:03
   ------------- -------------------------- 8.1/24.4 MB 9.0 MB/s eta 0:00:02
   ----------------- ---------------------- 10.7/24.4 MB 9.6 MB/s eta 0:00:02
   --------------------- ------------------ 13.1/24.4 MB 9.9 MB/s eta 0:00:02
   ----------------------- ---------------- 14.4/24.4 MB 9.7 MB/s eta 0:00:02
   --------------------------- ------------ 17.0/24.4 MB 9.8 MB/s eta 0:00:01
   ------------------------------ --------- 18.9/24.4 MB 9.7 MB/s eta 0:00:01
   ---------------------------------- ----- 21.0/24.4 MB 9.7 MB/s eta 0:00:01
   ------------------------------------- -- 22.8/24.4 MB 9.6 MB/s eta 0:00:01

In [ ]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

#### Pretrained Google Word2Vec Model

In [2]:
import gensim.downloader as api
word_vector = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [3]:
king_vector = word_vector['king']
king_vector

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [17]:
# Gets a word's vector
word_vector.get_vector('king')

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [4]:
king_vector.shape

(300,)

In [ ]:
# Find similar words
word_vector.most_similar('football')

[('soccer', 0.731354832649231),
 ('fooball', 0.7139959335327148),
 ('Football', 0.7124834060668945),
 ('basketball', 0.668246865272522),
 ('footbal', 0.6649289727210999),
 ('athletics', 0.6265192627906799),
 ('gridiron', 0.6191604733467102),
 ('baseball', 0.6162001490592957),
 ('footballl', 0.6069177985191345),
 ('sports', 0.5927178859710693)]

In [10]:
# Compare two words
word_vector.similarity('ronaldo','madrid')

np.float32(0.7830895)

In [ ]:
# Find the odd word
word_vector.doesnt_match(['football', 'cricket', 'tennis', 'apple'])

'apple'

In [15]:
vector = word_vector['man'] - word_vector['boy'] + word_vector['girl']
vector

array([ 2.29492188e-01, -3.04412842e-02,  5.85937500e-03, -3.02734375e-02,
        9.86328125e-02, -9.27734375e-02, -1.93359375e-01, -2.14233398e-02,
        5.10253906e-02,  8.22067261e-02, -7.17773438e-02, -3.02734375e-01,
       -1.35986328e-01, -1.25000000e-01,  6.88476562e-02,  4.87823486e-02,
       -4.39453125e-02, -1.16630554e-01,  1.03271484e-01, -2.35107422e-01,
       -1.66969299e-01, -1.53045654e-02, -1.49921417e-01, -4.01000977e-01,
        5.90820312e-02, -1.42578125e-01, -4.77294922e-02,  2.23632812e-01,
        3.51562500e-01, -1.82128906e-01,  6.63452148e-02,  7.38525391e-02,
       -9.37500000e-02, -1.26831055e-01, -1.67968750e-01,  1.76757812e-01,
        1.77734375e-01, -2.58789062e-02,  8.78906250e-03,  3.41796875e-01,
       -1.54541016e-01, -3.93066406e-02,  1.39648438e-01, -8.17565918e-02,
        1.64062500e-01, -3.00537109e-01, -9.42382812e-02, -1.17187500e-02,
        3.17382812e-02,  1.42456055e-01, -8.12988281e-02,  1.04492188e-01,
        1.40380859e-01, -

In [16]:
word_vector.most_similar([vector])

[('woman', 0.8696461319923401),
 ('man', 0.8103324770927429),
 ('girl', 0.7186311483383179),
 ('teenage_girl', 0.6898210048675537),
 ('lady', 0.6036313772201538),
 ('teenaged_girl', 0.5665764808654785),
 ('teenager', 0.5636714100837708),
 ('policewoman', 0.5580857992172241),
 ('prostitute', 0.5544335246086121),
 ('person', 0.5433641672134399)]

In [ ]:
# Checks if word exists
'laptop' in word_vector

True

### Training Word2Vec from Scratch: CBOW and Skip-Gram

#### CBOW (Continuous Bag of Words)

In [20]:
from gensim.models import Word2Vec

In [37]:
corpus = [
    "go until jurong point crazy available",
    "ok lar joking wif u oni",
    "free entry wkly comp win cup final"
]

In [39]:
tokenized_corpus = [sentence.split() for sentence in corpus]
tokenized_corpus

[['go', 'until', 'jurong', 'point', 'crazy', 'available'],
 ['ok', 'lar', 'joking', 'wif', 'u', 'oni'],
 ['free', 'entry', 'wkly', 'comp', 'win', 'cup', 'final']]

In [40]:
print(tokenized_corpus[0])

['go', 'until', 'jurong', 'point', 'crazy', 'available']


##### Train CBOW from scratch

In [ ]:
from gensim.models import word2vec

# Train CBOW Word2Vec model
cbow_model = Word2Vec(
    sentences=tokenized_corpus, # Training sentences
    vector_size=100,            # Each word will have 100 numbers
    window=3,                   # Context window size
    min_count=1,                # Ignore words appearing less than 1 time
    sg=0,                       # 0 = CBOW, 1 = Skip-Gram
    epochs=10                   # Train the model 10 times=10 
)

In [ ]:
# Check all words in the vocabulary
print(cbow_model.wv.index_to_key)

['final', 'cup', 'win', 'comp', 'wkly', 'entry', 'free', 'oni', 'u', 'wif', 'joking', 'lar', 'ok', 'available', 'crazy', 'point', 'jurong', 'until', 'go']


In [43]:
cbow_model.wv['free']

array([ 8.13227147e-03, -4.45733406e-03, -1.06835726e-03,  1.00636482e-03,
       -1.91113955e-04,  1.14817743e-03,  6.11386076e-03, -2.02715401e-05,
       -3.24596534e-03, -1.51072862e-03,  5.89729892e-03,  1.51410222e-03,
       -7.24261976e-04,  9.33324732e-03, -4.92128357e-03, -8.38409644e-04,
        9.17541143e-03,  6.74942741e-03,  1.50285603e-03, -8.88256077e-03,
        1.14874600e-03, -2.28825561e-03,  9.36823711e-03,  1.20992784e-03,
        1.49006362e-03,  2.40640994e-03, -1.83600665e-03, -4.99963388e-03,
        2.32429506e-04, -2.01418041e-03,  6.60093315e-03,  8.94012302e-03,
       -6.74754381e-04,  2.97701475e-03, -6.10765442e-03,  1.69932481e-03,
       -6.92623248e-03, -8.69402662e-03, -5.90020278e-03, -8.95647518e-03,
        7.27759488e-03, -5.77203138e-03,  8.27635173e-03, -7.24354526e-03,
        3.42167495e-03,  9.67499893e-03, -7.78544787e-03, -9.94505733e-03,
       -4.32914635e-03, -2.68313056e-03, -2.71289347e-04, -8.83155130e-03,
       -8.61755759e-03,  

In [42]:
cbow_model.wv['nlp']

KeyError: "Key 'nlp' not present"

##### Train Skip-Gram  from scratch

In [45]:
from gensim.models import Word2Vec

# Train Skip-Gram Word2Vec model
skipgram_model = Word2Vec(
    sentences=tokenized_corpus,     # Training sentences
    vector_size=100,                # Each word gets 100 numbers
    window=3,                       # Context window size
    min_count=1,                    # Keep words appearing at least 1 time
    sg=1,                           # 0 = CBOW, 1 = Skip-Gram
    epochs=10                       # Train the model 10 times
)

In [46]:
# Get the vector for a word
skipgram_model.wv['free']

array([ 8.13227147e-03, -4.45733406e-03, -1.06835726e-03,  1.00636482e-03,
       -1.91113955e-04,  1.14817743e-03,  6.11386076e-03, -2.02715401e-05,
       -3.24596534e-03, -1.51072862e-03,  5.89729892e-03,  1.51410222e-03,
       -7.24261976e-04,  9.33324732e-03, -4.92128357e-03, -8.38409644e-04,
        9.17541143e-03,  6.74942741e-03,  1.50285603e-03, -8.88256077e-03,
        1.14874600e-03, -2.28825561e-03,  9.36823711e-03,  1.20992784e-03,
        1.49006362e-03,  2.40640994e-03, -1.83600665e-03, -4.99963388e-03,
        2.32429506e-04, -2.01418041e-03,  6.60093315e-03,  8.94012302e-03,
       -6.74754381e-04,  2.97701475e-03, -6.10765442e-03,  1.69932481e-03,
       -6.92623248e-03, -8.69402662e-03, -5.90020278e-03, -8.95647518e-03,
        7.27759488e-03, -5.77203138e-03,  8.27635173e-03, -7.24354526e-03,
        3.42167495e-03,  9.67499893e-03, -7.78544787e-03, -9.94505733e-03,
       -4.32914635e-03, -2.68313056e-03, -2.71289347e-04, -8.83155130e-03,
       -8.61755759e-03,  

In [47]:
# Find words similar to "free"
skipgram_model.wv.most_similar('free')

[('jurong', 0.1637915074825287),
 ('win', 0.14595143496990204),
 ('go', 0.07480262219905853),
 ('joking', 0.05048147216439247),
 ('comp', 0.041577354073524475),
 ('wkly', 0.03476494178175926),
 ('entry', 0.01915225386619568),
 ('final', 0.016135703772306442),
 ('available', 0.01281448733061552),
 ('u', 0.008823923766613007)]

In [48]:
# Compare two words
skipgram_model.wv.similarity('free', 'entry')

np.float32(0.01915227)

In [49]:
cbow_model.wv.similarity('free', 'entry')

np.float32(0.01915227)

In [50]:
print(len(cbow_model.wv['free']))
print(len(skipgram_model.wv['free']))

100
100
